# Generated by Django 5.2.6 on 2025-09-23 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('chartsofaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartsofaccounts.chartsofaccounts')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipt', to='transactions.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='CashDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('particulars', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wht_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_disbursement', to='transactions.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('terms', models.CharField(blank=True, max_length=100, null=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='transactions.journalentry')),
            ],
        ),
    ]
