# Generated by Django 5.2.6 on 2025-10-08 05:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('chartsofaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('terms', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_return_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('purchase_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('wht_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('disbursement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_disbursements', to='chartsofaccounts.chartsofaccounts')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
            ],
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales_return_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('sales_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('wht_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='chartsofaccounts.chartsofaccounts')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')])),
                ('particulars', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartsofaccounts.chartsofaccounts')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
            ],
        ),
    ]
