# Generated by Django 5.2.6 on 2025-10-09 08:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('business', '0001_initial'),
        ('chartsofaccounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')])),
                ('particulars', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartsofaccounts.chartsofaccounts')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.bank')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('calendar_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_terms', to='transactions.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.paymenttype'),
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.transactiontype'),
        ),
    ]
