# Generated by Django 5.2.6 on 2025-10-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdisbursement',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='cashdisbursement',
            name='calendar_year',
        ),
        migrations.RemoveField(
            model_name='cashreceipt',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='cashreceipt',
            name='calendar_year',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='calendar_year',
        ),
        migrations.DeleteModel(
            name='GeneralJournal',
        ),
    ]
