# Generated by Django 5.2.6 on 2025-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_cashdisbursement_business_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalline',
            name='credit_amount',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='debit_amount',
        ),
        migrations.AddField(
            model_name='journalline',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='type',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10, null=True),
        ),
    ]
