# Generated by Django 5.2.6 on 2025-10-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('chartsofaccounts', '0005_alter_accounttype_unique_together_and_more'),
        ('transactions', '0003_remove_journalline_credit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashdisbursement',
            old_name='particulars',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cashreceipt',
            old_name='particulars',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cashreceipt',
            old_name='invoice_number',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_receipts', to='chartsofaccounts.chartsofaccounts'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit'),
        ),
        migrations.AddField(
            model_name='cashreceipt',
            name='calendar_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear'),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_receipt', to='transactions.journalentry'),
        ),
    ]
