# Generated by Django 5.2.6 on 2025-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_journalentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='transaction_type',
            field=models.CharField(choices=[('Cash Disbursement', 'Cash Disbursement'), ('Cash Receipt', 'Cash Receipt'), ('Journal Entry', 'Journal Entry'), ('Sales Invoice', 'Sales Invoice'), ('Purchase Invoice', 'Purchase Invoice')], max_length=50),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
