# Generated by Django 5.2.6 on 2025-10-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_rename_particulars_cashdisbursement_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashreceipt',
            name='sales_amount',
        ),
    ]
