# Generated by Django 5.2.6 on 2025-10-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_cashreceipt_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='sales_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
