# Generated by Django 5.2.6 on 2025-10-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_cashreceipt_sales_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceipt',
            name='sales_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='sales_return_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='wht_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
