# Generated by Django 5.2.6 on 2025-10-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('chartsofaccounts', '0005_alter_accounttype_unique_together_and_more'),
        ('transactions', '0007_alter_cashreceipt_sales_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdisbursement',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_disbursements', to='chartsofaccounts.chartsofaccounts'),
        ),
        migrations.AddField(
            model_name='cashdisbursement',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit'),
        ),
        migrations.AddField(
            model_name='cashdisbursement',
            name='calendar_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.calendaryear'),
        ),
    ]
