# Generated by Django 5.2.6 on 2025-10-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_cashdisbursement_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashdisbursement',
            old_name='invoice_number',
            new_name='reference',
        ),
    ]
