# Generated by Django 5.2.6 on 2025-10-03 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_rename_invoice_number_cashdisbursement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Amount must be greater than 0')]),
        ),
    ]
