# Generated by Django 5.2.6 on 2025-10-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_journalline_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashdisbursement',
            old_name='purchase_amount',
            new_name='disbursement_amount',
        ),
    ]
