# Generated by Django 5.2.6 on 2025-10-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_rename_purchase_amount_cashdisbursement_disbursement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdisbursement',
            name='purchase_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashdisbursement',
            name='purchase_return_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='cashdisbursement',
            name='wht_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
