# Generated by Django 5.2.6 on 2025-09-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_calendaryear'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaryear',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
