# Generated by Django 5.2.6 on 2025-09-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_calendaryear_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendaryear',
            unique_together={('name',)},
        ),
    ]
