# Generated by Django 5.2.6 on 2025-10-08 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
            ],
            options={
                'unique_together': {('business_unit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CashFlowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
            ],
            options={
                'unique_together': {('business_unit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChartsOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit')),
                ('cash_flow_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartsofaccounts.cashflowtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartsofaccounts.accounttype')),
            ],
            options={
                'unique_together': {('business_unit', 'code', 'name')},
            },
        ),
    ]
