# Generated by Django 5.2.6 on 2025-10-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('chartsofaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chartsofaccounts',
            unique_together={('business_unit', 'name')},
        ),
    ]
