# Generated by Django 5.2.6 on 2025-09-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('chartsofaccounts', '0002_chartsofaccounts_business_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chartsofaccounts',
            unique_together={('business_unit', 'code', 'name')},
        ),
    ]
