# Generated by Django 5.2.6 on 2025-09-30 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('chartsofaccounts', '0003_alter_chartsofaccounts_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit'),
        ),
        migrations.AddField(
            model_name='cashflowtype',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business.businessunit'),
        ),
    ]
