# Generated by Django 5.2.6 on 2025-10-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('chartsofaccounts', '0004_accounttype_business_unit_cashflowtype_business_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('business_unit', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cashflowtype',
            unique_together={('business_unit', 'name')},
        ),
    ]
